// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package sqlcDB

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Note struct {
	ID        int32
	Createdby string
	Createdat pgtype.Timestamp
	Updatedat pgtype.Timestamp
	Content   string
	Llmresp   pgtype.Text
}
